// Auto-generated by scripts/sync-client.ts — DO NOT EDIT MANUALLY
// Edit CLIENT.md at the repo root, then run: npm run sync-client

export const clientConfig = {
  identity: {
    prenomDirigeant: "Prénom",
    nomDirigeant: "Nom",
    nomEntreprise: "Mon Entreprise",
    slogan: "Votre artisan de confiance",
  },
  contact: {
    telephone: "01 00 00 00 00",
    telephoneRaw: "+33100000000",
    email: "contact@example.fr",
    rue: "1 Rue Exemple",
    ville: "Paris",
    codePostal: "75001",
    region: "Île-de-France",
  },
  coordinates: {
    lat: 48.8566,
    lng: 2.3522,
  },
  horaires: {
    display: "Lun-Ven : 8h-18h | Sam : 9h-12h",
  },
  chiffres: {
    anneeCreation: 2010,
    anneesExperience: new Date().getFullYear() - 2010,
    projetsRealises: 200,
    clientsSatisfaits: 180,
  },
  google: {
    rating: 4.8,
    reviewCount: 47,
  },
  socialMedia: {
    facebook: "",
    instagram: "",
    google: "",
  },
  seo: {
    rayonIntervention: "30-50 km",
    certifications: ["Garantie Décennale", "RGE", "Qualibat"],
    assurance: "Assurance décennale et responsabilité civile professionnelle",
  },
} as const;
