import * as fs from "fs";
import * as path from "path";

const ROOT = path.resolve(__dirname, "..");
const CLIENT_MD_PATH = path.join(ROOT, "CLIENT.md");
const OUTPUT_PATH = path.join(ROOT, "lib", "config", "client.config.ts");

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function parseClientMd(content: string): Record<string, string> {
  const map: Record<string, string> = {};
  for (const line of content.split("\n")) {
    const match = line.match(/^([A-Z_]+):\s*"(.*)"/);
    if (match) {
      map[match[1]] = match[2];
    }
  }
  return map;
}

function get(map: Record<string, string>, key: string, fallback: string): string {
  return map[key] ?? fallback;
}

function extractNumber(map: Record<string, string>, key: string, fallback: number): number {
  const raw = map[key];
  if (!raw) return fallback;
  const n = Number(raw);
  return Number.isNaN(n) ? fallback : n;
}

function splitList(value: string): string[] {
  return value
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  // Graceful fallback: if CLIENT.md doesn't exist, generate defaults and exit 0
  if (!fs.existsSync(CLIENT_MD_PATH)) {
    console.log("⚠  CLIENT.md not found — using default config.");
    // Ensure output dir exists
    fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
    // Copy the template default (the file already committed as client.config.ts)
    if (fs.existsSync(OUTPUT_PATH)) {
      console.log("✓  lib/config/client.config.ts already exists, skipping.");
    } else {
      console.log("✓  Generating default lib/config/client.config.ts");
      generateConfig({});
    }
    process.exit(0);
  }

  const raw = fs.readFileSync(CLIENT_MD_PATH, "utf-8");
  const data = parseClientMd(raw);

  console.log(`✓  Parsed CLIENT.md — ${Object.keys(data).length} keys found.`);

  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  generateConfig(data);

  console.log(`✓  Generated ${path.relative(ROOT, OUTPUT_PATH)}`);
}

function generateConfig(data: Record<string, string>) {
  const g = (key: string, fb: string) => get(data, key, fb);
  const n = (key: string, fb: number) => extractNumber(data, key, fb);

  const anneeCreation = n("ANNEE_CREATION", 2010);
  const certifications = splitList(g("CERTIFICATIONS", "Garantie Décennale, RGE, Qualibat"));

  const output = `// Auto-generated by scripts/sync-client.ts — DO NOT EDIT MANUALLY
// Edit CLIENT.md at the repo root, then run: npm run sync-client

export const clientConfig = {
  identity: {
    prenomDirigeant: ${JSON.stringify(g("PRENOM_DIRIGEANT", "Prénom"))},
    nomDirigeant: ${JSON.stringify(g("NOM_DIRIGEANT", "Nom"))},
    nomEntreprise: ${JSON.stringify(g("NOM_ENTREPRISE", "Mon Entreprise"))},
    slogan: ${JSON.stringify(g("SLOGAN", "Votre artisan de confiance"))},
  },
  contact: {
    telephone: ${JSON.stringify(g("TELEPHONE", "01 00 00 00 00"))},
    telephoneRaw: ${JSON.stringify(g("TELEPHONE_RAW", "+33100000000"))},
    email: ${JSON.stringify(g("EMAIL", "contact@example.fr"))},
    rue: ${JSON.stringify(g("RUE", "1 Rue Exemple"))},
    ville: ${JSON.stringify(g("VILLE", "Paris"))},
    codePostal: ${JSON.stringify(g("CODE_POSTAL", "75001"))},
    region: ${JSON.stringify(g("REGION", "Île-de-France"))},
  },
  coordinates: {
    lat: ${n("LATITUDE", 48.8566)},
    lng: ${n("LONGITUDE", 2.3522)},
  },
  horaires: {
    display: ${JSON.stringify(g("HORAIRES_DISPLAY", "Lun-Ven : 8h-18h | Sam : 9h-12h"))},
  },
  chiffres: {
    anneeCreation: ${anneeCreation},
    anneesExperience: new Date().getFullYear() - ${anneeCreation},
    projetsRealises: ${n("PROJETS_REALISES", 200)},
    clientsSatisfaits: ${n("CLIENTS_SATISFAITS", 180)},
  },
  google: {
    rating: ${n("GOOGLE_RATING", 4.8)},
    reviewCount: ${n("GOOGLE_REVIEW_COUNT", 47)},
  },
  socialMedia: {
    facebook: ${JSON.stringify(g("FACEBOOK", ""))},
    instagram: ${JSON.stringify(g("INSTAGRAM", ""))},
    google: ${JSON.stringify(g("GOOGLE_BUSINESS", ""))},
  },
  seo: {
    rayonIntervention: ${JSON.stringify(g("RAYON_INTERVENTION", "30-50 km"))},
    certifications: ${JSON.stringify(certifications)},
    assurance: ${JSON.stringify(g("ASSURANCE", "Assurance décennale et responsabilité civile professionnelle"))},
  },
} as const;
`;

  fs.writeFileSync(OUTPUT_PATH, output, "utf-8");
}

main();
